//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotosteam.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fotosteam.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; möchte Dich als Buddy hinzufügen. Bestätige die Anfrage auf:
        ///&lt;br /&gt;&lt;br /&gt;
        ///&lt;a href=&quot;##userUrl##&quot;&gt;##userUrl##&lt;/a&gt;
        ///.
        /// </summary>
        internal static string BuddyAdd_de {
            get {
                return ResourceManager.GetString("BuddyAdd_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; want to add you as a buddy. Confirm the request on:
        ///&lt;br /&gt;&lt;br /&gt;
        ///&lt;a href=&quot;##userUrl##&quot;&gt;##userUrl##&lt;/a&gt;
        ///.
        /// </summary>
        internal static string BuddyAdd_en {
            get {
                return ResourceManager.GetString("BuddyAdd_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; hat Dich als Buddy bestätigt..
        /// </summary>
        internal static string BuddyConfirmation_de {
            get {
                return ResourceManager.GetString("BuddyConfirmation_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; confirmed you as a buddy.
        ///.
        /// </summary>
        internal static string BuddyConfirmation_en {
            get {
                return ResourceManager.GetString("BuddyConfirmation_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;salutation&quot;: &quot;Hallo %1&quot;,
        ///    &quot;complimentary-close-1&quot;: &quot;Viele Grüße&quot;,
        ///    &quot;complimentary-close-2&quot;: &quot;Dein Fotosteam&quot;,
        ///    &quot;disclaimer&quot;: &quot;Falls Du keine Emails mehr erhalten willst, dann ändere bitte Deine Benachrichtungseinstellung.&quot;,
        ///    &quot;beta-disclaimer&quot;: &quot;Fotosteam ist noch in der Betaphase.&quot;,
        ///    &quot;rating-title&quot;: &quot;Neue Fotobewertung&quot;,
        ///	&quot;rating-value-star&quot;: &quot;1 Stern&quot;,
        ///	&quot;rating-value-stars&quot;: &quot;%1 Sternen&quot;,
        ///	&quot;comment-title&quot;: &quot;Neuer Fotokommentar&quot;,
        ///    &quot;buddy-add-title&quot;: &quot;Neue Buddyanfrage&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mail_de_json {
            get {
                return ResourceManager.GetString("mail_de_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;salutation&quot;: &quot;Hallo %1&quot;,
        ///    &quot;complimentary-close-1&quot;: &quot;Cheers&quot;,
        ///    &quot;complimentary-close-2&quot;: &quot;Fotosteam&quot;,
        ///    &quot;disclaimer&quot;: &quot;If you prefer not to receive any emails from Fotosteam please adjust your email settings.&quot;,
        ///    &quot;beta-disclaimer&quot;: &quot;Fotosteam is still in beta mode.&quot;,
        ///    &quot;rating-title&quot;: &quot;New photo rating&quot;,
        ///	&quot;rating-value-star&quot;: &quot;1 star&quot;,
        ///	&quot;rating-value-stars&quot;: &quot;%1 stars&quot;,
        ///	&quot;comment-title&quot;: &quot;New photo comment&quot;,
        ///    &quot;buddy-add-title&quot;: &quot;New buddy request&quot;,
        ///    &quot;buddy-confirmation-titl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mail_en_json {
            get {
                return ResourceManager.GetString("mail_en_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;!--https://github.com/mailchimp/Email-Blueprints--&gt;
        ///&lt;!--http://templates.mailchimp.com/resources/inline-css/--&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;##title##&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /***CLIENT-SPECIFIC STYLES***/
        ///        #outlook a {
        ///            padding: 0;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mail_template_inline {
            get {
                return ResourceManager.GetString("mail_template_inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;!--https://github.com/mailchimp/Email-Blueprints--&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;##title##&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /***CLIENT-SPECIFIC STYLES***/
        ///        #outlook a {
        ///            padding: 0;
        ///        }
        ///        /* Force Outlook to provide a &quot;view in bro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mail_template_responsive {
            get {
                return ResourceManager.GetString("mail_template_responsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; hat dein Foto 
        ///&lt;a href=&quot;https://www.fotosteam.com/##alias##/foto/##photoname##&quot;&gt;##phototitle##&lt;/a&gt; 
        ///kommentiert:
        ///&lt;br /&gt;
        ///&lt;pre&gt;##comment##&lt;/pre&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;img src=&quot;##photourl##&quot; /&gt;.
        /// </summary>
        internal static string NewComment_de {
            get {
                return ResourceManager.GetString("NewComment_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; commented your photo 
        ///&lt;a href=&quot;https://www.fotosteam.com/##alias##/foto/##photoname##&quot;&gt;##phototitle##&lt;/a&gt;: 
        ///&lt;br /&gt;
        ///&lt;pre&gt;##comment##&lt;/pre&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;img src=&quot;##photourl##&quot; /&gt;.
        /// </summary>
        internal static string NewComment_en {
            get {
                return ResourceManager.GetString("NewComment_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; hat ein neues Foto 
        ///&lt;a href=&quot;https://www.fotosteam.com/##userAlias##/foto/##photoname##&quot;&gt;##phototitle##&lt;/a&gt; 
        ///hinzugefügt. 
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;img src=&quot;##photourl##&quot; /&gt;.
        /// </summary>
        internal static string NewPhoto_de {
            get {
                return ResourceManager.GetString("NewPhoto_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; uploaded a new photo 
        ///&lt;a href=&quot;https://www.fotosteam.com/##userAlias##/foto/##photoname##&quot;&gt;##phototitle##&lt;/a&gt;. 
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;img src=&quot;##photourl##&quot; /&gt;
        ///.
        /// </summary>
        internal static string NewPhoto_en {
            get {
                return ResourceManager.GetString("NewPhoto_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; hat dein Foto 
        ///&lt;a href=&quot;https://www.fotosteam.com/##alias##/foto/##photoname##&quot;&gt;##phototitle##&lt;/a&gt; 
        ///mit &lt;strong&gt;##rating##&lt;/strong&gt; bewertet.
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;img src=&quot;##photourl##&quot; /&gt;
        ///.
        /// </summary>
        internal static string NewRating_de {
            get {
                return ResourceManager.GetString("NewRating_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;##userAlias##&lt;/strong&gt; rated your photo 
        ///&lt;a href=&quot;https://www.fotosteam.com/##alias##/foto/##photoname##&quot;&gt;##phototitle##&lt;/a&gt; 
        ///with &lt;strong&gt;##rating##&lt;/strong&gt;.
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;img src=&quot;##photourl##&quot; /&gt;
        ///.
        /// </summary>
        internal static string NewRating_en {
            get {
                return ResourceManager.GetString("NewRating_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte beachten:
        ///
        ///Fotos bitte nur in den ToPublish-Ordner kopieren.
        ///
        ///Die Struktur von Internal bitte nicht ändern, da dies zu ungewünschten Seiteneffekten führen kann und eventuell der Auftritt
        ///bei Fotosteam nicht mehr korrekt funktioniert.
        ///
        ///-----------------------------------------------------------------------------------------------------------------------------
        ///
        ///Please note:
        ///
        ///Place your folders only into the ToPublish folder. 
        ///
        ///Do not make any changes to the folder structure within the inter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
    }
}
